version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Install dependencies
          command: npm install  
      - save_cache:
          paths:
            - node_modules
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Delete previous deployment files
          command: |
            git clone https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git public
            cd public
            git status
            #delete everything except the .git dir
            find * -maxdepth 0 -name '.git' -prune -o -exec rm -rf '{}' ';'
            echo "Files after deletion:"
            ls -a
            git config --global user.email "bryan@iocharged.com"
            git config --global user.name "Bryan McConnahea"
            git commit -am "Remove previous deploy files"
            git status
      - run:
          name: Gatsby Build
          command: npm run build
      - run:
          name: Transfer deploy extra files
          command: cp ./_deploy/public/* ./public
      - run:
          name: Init Git Repo in Public
          command: |
            cd public
            git add .
            git commit -am "CirleCI deployment"
            git status
      - run:
          name: List Files
          command: ls -a . && ls -a ./public
      - run:
          name: Deploy Master to Heroku
          command: |
            cd public
            pwd
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  deploy_heroku:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  deploy_now:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Install Now CLI
          command: npm install now
      - run:
          name: Deploy to Now
          command: ls public && cd public && now alias https://public-brtlxzndss.now.sh/ gatsby-start
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build